// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, LoginTeacher, Spine, formUtil, langResourceCommon, rfl, _ref;
    $ = require('jquery');
    Spine = require('spine');
    rfl = require('rfl');
    langResourceCommon = require('lang/{{G.LANG}}/common');
    formUtil = require('form-util');
    LoginTeacher = (function(_super) {
      __extends(LoginTeacher, _super);

      function LoginTeacher() {
        _ref = LoginTeacher.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      LoginTeacher.prototype.events = {
        'click [data-login-btn]': 'login'
      };

      LoginTeacher.prototype.teacherTpl = require('../views/login-teacher.tpl.html');

      LoginTeacher.prototype.init = function() {
        return this.render();
      };

      LoginTeacher.prototype.render = function() {
        return this.html(this.teacherTpl.render());
      };

      LoginTeacher.prototype.login = function() {
        var data;
        data = formUtil.getData('#teacher-login-form');
        if (!data.username) {
          alert('请输入用户名');
          return;
        }
        if (!data.password) {
          alert('请输入密码');
          return;
        }
        return rfl.ajax.post({
          url: "loginAsTeacher",
          data: {
            username: data.username,
            password: data.password
          },
          success: function(res) {
            if (res.code === 0) {
              return rfl.util.gotoUrl("teacher/dashboard");
            } else {
              return rfl.alerts.show(res.message, 'error');
            }
          }
        });
      };

      return LoginTeacher;

    })(Spine.Controller);
    return LoginTeacher;
  });

}).call(this);
