// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, Login, Spine, StudentLogin, TeacherLogin, langResourceAdRemark, langResourceCommon, rfl, _ref;
    $ = require('jquery');
    Spine = require('spine');
    rfl = require('rfl');
    langResourceCommon = require('lang/{{G.LANG}}/common');
    langResourceAdRemark = require('lang/{{G.LANG}}/ad-remark');
    StudentLogin = require('./login-student');
    TeacherLogin = require('./login-teacher');
    Login = (function(_super) {
      __extends(Login, _super);

      function Login() {
        _ref = Login.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Login.prototype.events = {
        'click .teacher-btn': 'loginAsTeacher',
        'click .student-btn': 'loginAsStudent'
      };

      Login.prototype.mainTpl = require('../views/login-main.tpl.html');

      Login.prototype.studentLoginTpl = require('../views/login-student.tpl.html');

      Login.prototype.teacherLoginTpl = require('../views/login-teacher.tpl.html');

      Login.prototype.init = function() {
        return this.render();
      };

      Login.prototype.render = function() {
        return this.html(this.mainTpl.render());
      };

      Login.prototype.loginAsStudent = function() {
        return new StudentLogin({
          el: "#main-div"
        });
      };

      Login.prototype.loginAsTeacher = function() {
        console.log('loginAsTeacher');
        return new TeacherLogin({
          el: "#main-div"
        });
      };

      return Login;

    })(Spine.Controller);
    return Login;
  });

}).call(this);
