// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, LoginStudent, Spine, langResourceCommon, rfl, _ref;
    $ = require('jquery');
    Spine = require('spine');
    rfl = require('rfl');
    langResourceCommon = require('lang/{{G.LANG}}/common');
    LoginStudent = (function(_super) {
      __extends(LoginStudent, _super);

      function LoginStudent() {
        _ref = LoginStudent.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      LoginStudent.prototype.events = {
        'click [data-login-btn]': 'login'
      };

      LoginStudent.prototype.mainTpl = require('../views/login-student.tpl.html');

      LoginStudent.prototype.init = function() {
        return this.render();
      };

      LoginStudent.prototype.render = function() {
        return this.html(this.mainTpl.render());
      };

      LoginStudent.prototype.login = function() {
        return rfl.util.gotoUrl('student/dashboard');
      };

      return LoginStudent;

    })(Spine.Controller);
    return LoginStudent;
  });

}).call(this);
