// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, Spine, ViewGrade, langResourceCommon, rfl, _ref;
    $ = require('jquery');
    Spine = require('spine');
    rfl = require('rfl');
    langResourceCommon = require('lang/{{G.LANG}}/common');
    ViewGrade = (function(_super) {
      __extends(ViewGrade, _super);

      function ViewGrade() {
        _ref = ViewGrade.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ViewGrade.prototype.gradeListTpl = require('../views/grade-list.tpl.html');

      ViewGrade.prototype.init = function() {
        return this.render();
      };

      ViewGrade.prototype.render = function() {
        return this.html(this.gradeListTpl.render());
      };

      return ViewGrade;

    })(Spine.Controller);
    return ViewGrade;
  });

}).call(this);
